### ISSUE TITLE
Naas drivers : !pip3 install pymongo[srv]

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/drivers#116]
Install pymongo[srv] to connect to mongoDB in driver

**Comment by Dr0p42** [comment]
@FlorentLvr it seems that this is already available https://github.com/jupyter-naas/naas/blob/5f670344499633a560047244d535cf78946037b2/setup.py#L72

You should not have to install `pymongo[srv]` yourself. Could you provide the error you are getting please?
