### ISSUE TITLE
Codec Error while pip install naas_drivers 

### ISSUE THREAD

**Issue by yaswanthkumargothi** [jupyter-naas/drivers#129]
Environment

- Windows 8.1
- Conda-4.10.3
- python 3.8

Error : Command errored out with exit status 1: python setup.py egg_info check the logs for more info

Error elaborated: UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1130: character maps to <undefined>

Setup.py  line 4 long_description = fh.read() is causing this error

**Comment by yaswanthkumargothi** [comment]
Its due to Windows system default encoding as the encoding is not provided in the open() method. Older Window's machines uses `cp1252` encoding

Refer this: https://stackoverflow.com/questions/36303919/python-3-0-open-default-encoding/36316351#36316351

Solution: add encoding to the open() in setup.py

      with open("README.md", "r", encoding ='utf-8') as fh:         
         long_description = fh.read()

**Comment by jravenel** [comment]
Fixed.
