### ISSUE TITLE
LinkedIn. get_posts_stats() Does not recognize LinkedIn Polls and LinkedIn Shares Posts

### ISSUE THREAD

**Issue by mellamomark** [jupyter-naas/drivers#135]
I noticed when using `linkedin.connect(LI_AT, JSESSIONID).profile.get_posts_stats(PROFILE_URL)` I was having data quality issues where I had 0 views, which is unlikely on this platform.
![Screen Shot 2021-07-18 at 6 20 54 PM](https://user-images.githubusercontent.com/33115104/126089407-73bb7125-be26-46c7-abf1-b25eeaba1ebb.png)

When clicking into the provided URLs I was taken to the following screen:
![Screen Shot 2021-07-18 at 6 23 27 PM](https://user-images.githubusercontent.com/33115104/126089557-86b34a84-69cb-4b86-af67-5b3f44475525.png)

Upon further inspection, it seems that 1) this function struggles to pick up LinkedIn poll posts, and 2) when sharing posts from other users, it attributes the shared post as your own with 0 for all stats. Examples of such posts are below:
![Screen Shot 2021-07-18 at 6 28 07 PM](https://user-images.githubusercontent.com/33115104/126089900-85a86ae7-ca89-44c1-b502-d37ddceb60d7.png)
![Screen Shot 2021-07-18 at 6 26 04 PM](https://user-images.githubusercontent.com/33115104/126089902-46aa7a80-9fc0-47e6-b1a8-922753aa40fd.png)

**Comment by FlorentLvr** [comment]
Hello @mellamomark,

Thank you for your feedback.
We didn't plan that case so we will look into it and get back to you ASAP.

**Comment by FlorentLvr** [comment]
@mellamomark, sorry for the late reply. 
We have updated our LinkedIn driver to get stats post and get all posts from your profile and that fix your issue. The new version is available on naas 2.1.15.

![image](https://user-images.githubusercontent.com/48032461/150950048-94796024-780d-4da2-85dd-56a44a3bf399.png)
