### ISSUE TITLE
Newsapi - Typeerror due to typo in get method

### ISSUE THREAD

**Issue by yaswanthkumargothi** [jupyter-naas/drivers#138]
**Newsapi driver Type error**

Error: `TypeError: get() got multiple values for argument 'fields'`

going through the code, `get` method has "image" specified twice
 
` def get(self, fields=["image", "title", "image", "link"], limit=20, **kargs):`

**Comment by yaswanthkumargothi** [comment]
I tested copying the entire driver and changing one of the `"image"` variables to `"source"`. And It works fine now. 

FYI: `fields` parameter for all the functions in Newsapi driver need to be changed

**Comment by tparente-ui** [comment]
Hi @FlorentLvr, i made a fix on this issue, could you please review when you have some time please ?
