### ISSUE TITLE
Notion - Update driver with API methods

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/drivers#157]
List of formulas we could develop to update current drivers

## Connect 

token = "*********"
naas_drivers.notion.connect(token)

## Get page 
url = "*********"
naas_drivers.notion.connect(token).page.get(url)

## Get database 
url = "*********"
naas_drivers.notion.connect(token).database.get(url)

## Create page 

parent_id = "*********" #can be id of wokspace or id or parent page
naas_drivers.notion.connect(token).page.create(parent_id, properties,  content)

Add properties

properties.name = "The name of my page"
properties.created_date = "14/09/2021"

content.heading1 = "My heading 1"
content.heading2 = "My heading 2"

To be developped further @axelearning @FlorentLvr

**Comment by axelearning** [comment]
☝️ Take a look at my PR @jravenel

**Comment by axelearning** [comment]
As @tparente-ui has refactored the driver, an after the workshop with him and @jravenel : 

We have created a new PR to extend the functionality of notion driver
