### ISSUE TITLE
LinkedIn Driver - profile.get_posts_feed returns incorrect post dates 

### ISSUE THREAD

**Issue by njgroene** [jupyter-naas/drivers#262]
In the DataFrame returned by **profile.get_posts_feed**, the values of **PUBLISHED_DATE** are identical for all rows, at least when used on your own profile (the profile connecting to LI through the driver). 

Related issue: the column **PAGINATION_TOKEN** also contains the same value for all rows.

![Capture](https://user-images.githubusercontent.com/8094460/162993061-6b7bcb70-eccd-46a8-a333-59b1b57ea314.JPG)

**Comment by FlorentLvr** [comment]
Hi @njgroene !

TY for your feedback.

If you used the template "LinkedIn_Get_posts_stats_from_profile.ipynb", this is not a bug but the normal behaviour : 
![image](https://user-images.githubusercontent.com/48032461/162995121-13df09c2-bdfa-40df-9529-e2247d310aa7.png)
This template should be used only to get dynamic data. 
Maybe it's not clear enough. 
Let us know how we could improve that.

You should use "LinkedIn_Get_posts_feed_from_profile.ipynb" to get all your post data with the correct date.

**Comment by njgroene** [comment]
My bad, should have paid attention - thank you for the quick reply!

**Comment by jravenel** [comment]
I think we can maybe get rid of this one @FlorentLvr, Avery got the same issue last week.
