### ISSUE TITLE
Top 10 results only on googleanalytics.views.get_pageview

### ISSUE THREAD

**Issue by valentin-glt** [jupyter-naas/drivers#264]
Hello @Charles-de-Montigny !

It seems that ` googleanalytics.views.get_pageview` only returns 10 pages in the results. That is a problem because I need all pages views.

For instance, code snipet :
`df_pageview = googleanalytics.connect(json_path).views.get_pageview(view_id, start_date='2021-01-01', end_date='2021-01-31')`

I'll get no more than 10 rows in this dataframe.

Any idea what is the issue here ?

**Comment by FlorentLvr** [comment]
Fixed
