### ISSUE TITLE
Snowflake - Initiate driver

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/drivers#274]
Based on the current awesome-notebooks templates + python file in the Snowflake folder, the idea is to create the first naas_drivers and adapt the existing templates according to the syntax.

The syntax should look like : 

from naas_drivers import snowflake 

a = snowflake.connect("username","password", "account", "warehouse_name", "schema_name")

→ returns self

snowflake.connect(a).database.get("database", "table_name", query={"SELECT * FROM "})

→ returns pandas dataframe

**Comment by jravenel** [comment]
Hi @mckraqs, @Dr0p42, as discussed today, here is the good first issue we can work on to create a Snowflake naas_drivers

**Comment by Dr0p42** [comment]
Awesome @mckraqs 🚀 So happy to see that we are moving forward with Snowflake 💪
