### ISSUE TITLE
Email - get emails by specific subject, sender and date

### ISSUE THREAD

**Issue by garrrikkotua** [jupyter-naas/drivers#278]
Would be cool to add some features to the email driver, for instance:

`get_emails_by_subject(subject: str)`

`get_emails_by_date(date: datetime)`

`get_emails_by_sender(sender_email: str)`

I could try to make a PR for some of them :)

**Comment by Dr0p42** [comment]
👋 Hello @garrrikkotua , 

It would make it easier to create new automation around mailboxes 👍.

By looking at the documentation of the library used [here](https://github.com/ikvk/imap_tools#search-criteria) it should be fairly easy to implement :)

Thank you for opening this issue 👏

---

What do you think @FlorentLvr ?

**Comment by jravenel** [comment]
@garrrikkotua it's a good idea! do you think you can package the 3 in a PR?
