### ISSUE TITLE
feat: add stages to Snowflake driver

### ISSUE THREAD

**Issue by mckraqs** [jupyter-naas/drivers#307]
The goal for this issue is to implement stage creation, so data can be loaded from both local (computer) and external (cloud) location. For now, only batch ingestion is necessary, as Snowpipe (streaming) will require much more work.

More on that can be found below:

- https://docs.snowflake.com/en/user-guide-data-load.html
- https://docs.snowflake.com/en/sql-reference/sql/create-stage.html

I can work on this issue by myself. 

cc: @jravenel

**Comment by jravenel** [comment]
Thanks @mckraqs I'm putting this into the community roadmap → In progress. Let me know if you need anything.

**Comment by jravenel** [comment]
@mckraqs as discussed on Slack, let's update progress here :)

**Comment by mckraqs** [comment]
PR open, you can look into that @jravenel. 

So far driver has been updated with some redesign in terms of commands execution and extra API availability for objects like databases, schemas, stages. 

[Here](https://github.com/jupyter-naas/awesome-notebooks/pull/1131) you can find PR for awesome-notebooks that contains Snowflake driver basics usage. Soon I will move forward with driver update and examples for data ingestion.

cc: @Dr0p42 for extra check wdyt about `snowflake.api` dict as an access layer for functionalities. With this approach it can be easily extended for more Snowflake objects like file formats, stages, pipes, tasks, etc. (there's ton of them). Thanks for any suggestion!

**Comment by jravenel** [comment]
Thanks for your PR @mckraqs we talked about it yesterday during the community call and people are really excited. 
There will be a bunch of testers ready to give feedback. 

I let @Dr0p42 follow along for the technical side.

**Comment by mckraqs** [comment]
Good to hear that! PR is ready. I revamped the driver a bit, previous version seemed clumsy to me. 

There's a plenty of space for further development, although it looks like a first stable version 🎆
