### ISSUE TITLE
How to expose a production-grade Dash apps from naas cloud account?

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/drivers#313]
→ Discussed 22/08/2022, we can use https://knative.dev/docs/ to create a specific container for the deployment of a dash app (or any other app/process that would need to ensure reliability, secure, available via specific list of user/password) 

This is to be considered a project, that would have dependencies at infrastructure level (deployment system), driver level (access to deployment system), template level (example to deploy). There is also an administration issue to consider to make sure the owner of the naas cloud account can follow what is happening on the containers deployed (uptime, logs, credits/time consummed)

**Comment by FlorentLvr** [comment]
@jravenel, closing this issue as it will be develop in naas workspace
