### ISSUE TITLE
BigQuery - Init driver

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/drivers#318]

**Comment by FlorentLvr** [comment]
@MinuraPunchihewa , 
- duplicate an existing driver, I think sharepoint.py will be a good option
- create a connect and then add function to your driver in your py file
- test using it your notebook templates
- once your driver is done, update the init to call it with naas_drivers: https://github.com/jupyter-naas/drivers/blob/main/naas_drivers/__init__.py

Let me know if you have any more questions!

TY 🙏

**Comment by MinuraPunchihewa** [comment]
@FlorentLvr Understood. I will start working on this.
