### ISSUE TITLE
Add CI task "Update /drivers page in docs from drivers Readme.md"

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/drivers#331]
@chicken-biryani this is linked to your suggestion on the gdoc, I believe the readme and the landing page in the doc should be the same and hence be automated.

Current: https://docs.naas.ai/drivers
Source: https://github.com/jupyter-naas/drivers/blob/main/README.md
Target: https://github.com/jupyter-naas/docs/blob/master/drivers/README.md

**Comment by jravenel** [comment]
@MinuraPunchihewa you want to be the owner of this task? or maybe @mckraqs? This will make sure we start some decent refactoring of the readme and the contribution process should be directly in there like I did for the awesome-notebooks https://github.com/jupyter-naas/awesome-notebooks#how-to-contribute-

In here, there is no need to use naas cloud, you people can contribute from local or cloud. What's you take? 

cc @FlorentLvr @Dr0p42 thoughts?

**Comment by jravenel** [comment]
Have added #hacktoberfest and few other tags missing in this repo

**Comment by MinuraPunchihewa** [comment]
Hey @jravenel, sure I can take this up.

**Comment by jravenel** [comment]
Let's do a 1h workshop this week @MinuraPunchihewa? Better if we sync on that topic

**Comment by MinuraPunchihewa** [comment]
Sure @jravenel, when do we do it?

**Comment by jravenel** [comment]
Can you do this Thursday at 5PM CET ? We can make it a community event

**Comment by MinuraPunchihewa** [comment]
Hey @jravenel, my apologies, but this Thursday is a little tough for me. Is there any other time we can connect at?

**Comment by jravenel** [comment]
Do you mind booking a slot here? https://calendly.com/jeremyravenel that would be easier.

**Comment by MinuraPunchihewa** [comment]
@jravenel I set up some time for next week. I hope that is alright.

**Comment by jravenel** [comment]
Of course

**Comment by jravenel** [comment]
closing this to start fresh!
