### ISSUE TITLE
HubSpot API Key method is not supported anymore

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/drivers#338]
**Describe the bug**
Hubspot auth method change so we need to update the HS driver

**Screenshots**
<img width="1680" alt="Screenshot 2022-11-14 at 13 13 08" src="https://user-images.githubusercontent.com/21052349/201657344-d93103f5-8c89-4d45-b527-a23c597cb9bc.png">

**Additional context**
Reported by: 
- Simon (Prello)
- Derrick Kwa

**Comment by FlorentLvr** [comment]
@jravenel, now we need to create a private and pass the token inside the header. 

This modification will impact all users using the old method => Once naas will be restarted, they will have to create a private hubspot to keep using their integration.

Once, it will be done, I will update all templates in awesome-notebooks.

**Comment by FlorentLvr** [comment]
New message in input section: 

### Setup HubSpot 
👉 Starting November 30, 2022, HubSpot API keys no longer enable access to HubSpot APIs, so in Naas version 2.8 and above, you need [create a private app and use the access token.](https://developers.hubspot.com/docs/api/private-apps)

**Comment by FlorentLvr** [comment]
> New message in input section:
> 
> ### Setup HubSpot
> 👉 Starting November 30, 2022, HubSpot API keys no longer enable access to HubSpot APIs, so in Naas version 2.8.3 and above, you need [create a private app and use the access token.](https://developers.hubspot.com/docs/api/private-apps)

@jravenel => communication to be done

**Comment by FlorentLvr** [comment]
@jravenel 

:rotating_light: [HUBSPOT] MAJOR DRIVER UPDATE

:point_right: Starting November 30, 2022, HubSpot API keys no longer enable access to HubSpot APIs, so in Naas version 2.8.3 and above, you need create a private app and use the access token.

The new version is now available and you need to restart your naas to access it.

All templates related to HubSpot has been updated in the library. 

Feel free to come back if you have any troubles!
