### ISSUE TITLE
CICD not working "Error: Docker build failed with exit code 100"

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/drivers#363]
I fixed a bug on the notion driver to get page id but CICD does not work to create new drive package. 
Could you please help? 
https://github.com/jupyter-naas/drivers/actions/runs/4828347727/jobs/8602103145
![image](https://user-images.githubusercontent.com/48032461/235090122-6d1425df-b2cf-4bc6-8d38-fdc718a2c9f3.png)

**Comment by FlorentLvr** [comment]
@Dr0p42, still stuck on this. Could you please fix it 🙏 ?
https://github.com/jupyter-naas/drivers/actions/runs/5462846219/jobs/9942811680

**Comment by Dr0p42** [comment]
I fixed it by disabling the upload of the code coverage for now: https://github.com/jupyter-naas/drivers/actions/runs/5463095650/jobs/9943348787
