### ISSUE TITLE
Streamlit - Run app with driver

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/drivers#88]
Today, it's possible from Google colab to create an integration with Streamlit (dashboarding/apps) using a "ngrok". 
This could be also integrated in Naas as a driver. 
import naas 
naas.streamlit.add(source="mygraph.html", target="streamlit account")

https://naas.canny.io/requests/p/create-streamlit-driver

**Comment by jravenel** [comment]
Hey @gagan3012, could you please share the notebook needed to test? doing naas.asset.add('xxx.ipynb')

**Comment by jravenel** [comment]
Video from Gagan :  https://www.loom.com/share/b93012d8733942ff839737029d508aa6

**Comment by jravenel** [comment]
@gagan3012 @FlorentLvr @Dr0p42  I could not manage to launch the app and reproduce it in a notebook yet. 


I have the error: 
`TypeError                                 Traceback (most recent call last)
<ipython-input-10-8819a8084a93> in <module>
      1 import naas_drivers
----> 2 naas_drivers.NaasStreamlit.run_app("streamlit_app.py",port=9999)

TypeError: run_app() got an unexpected keyword argument 'port'`

Here is my notebook.
I think we should refactor the driver to make it consistent with our new Naas framework.

**Comment by gagan3012** [comment]
To run we need to do:
`NaasStreamlit("streamlit_app.py")`

@jravenel

**Comment by jravenel** [comment]
Ok that's really following the convention of other drivers.

The formula should like naas.streamlit.add("app.py")

Do you mind updating the driver ? @gagan3012 

Thanks 🙏

**Comment by jravenel** [comment]
> [](https://public.naas.ai/amVyZW15LTJFcmF2ZW5lbC00MGNhc2hzdG9yeS0yRWNvbQ==/asset/0fadcc735eaceda1bc3178057a42b8dec35085e6f43c7aebc8fa80e04f6e)
> 
> I think we should refactor the driver to make it consistent with our new Naas f

@tparente-ui you can see my notebook test here.
